---
title: "Zusammenfassung Neu"
author: "Kyrill Guba, Colin Linke, Batuhan Güyelkaya, Vaishali Iyer"
date: "2023-01-21"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
library(tidyverse) # Modern data science library 
library(plm)       # Panel data analysis library
library(car)       # Companion to applied regression 
library(ggplot2)    # Various programing tools for plotting data
library(tseries)   # For timeseries analysis
library(lmtest)
```

```{r datasets, include=TRUE}
df4 <- read.csv("df4.csv", header = TRUE, sep = ",")
df4_pan<-pdata.frame(df4,index=c("district","week"))

df_pan2<-df4_pan[-(which(df4_pan$week==1)),]

s<-data.frame(c(lag(df_pan2$inzidenz, 1)),c(lag(df_pan2$weightednbinz, 1)),
              c(I(log(df_pan2$density)*lag(df_pan2$inzidenz, 1))),
              c(I(df_pan2$hotspot*lag(df_pan2$inzidenz,1))),
              c(I(df_pan2$hotspotnb*lag(df_pan2$weightednbinz,1))),
              c(I(df_pan2$rate_zweitimpf * df_pan2$hotspot)),
              c(df_pan2$A60.79.Anteil))

colnames(s)<-c("inzidenz1","weightednbinz1","density_inzidenz1",
               "hotspot_inzidenz1", "hotspotnb_wnbinzidenz1",
               "zweitimpf_hotspot","A60.79.Anteil")


```



```{r pools, include=TRUE}
pool <- plm(inzidenz ~ lag(inzidenz, 1) + lag(weightednbinz, 1) 
            + I(log(density)*lag(inzidenz, 1)) + I(hotspot * lag(inzidenz, 1)) 
            +I(hotspotnb * lag(weightednbinz, 1)) + I(rate_zweitimpf * hotspot) 
            + A60.79.Anteil 
            + factor(week)
            , data =df4_pan, model = "pooling")

pool.sqrt <- plm(sqrt(inzidenz) ~ sqrt(lag(inzidenz, 1)) + sqrt(lag(weightednbinz, 1))
                 + sqrt(I(log(density)*lag(inzidenz, 1))) + sqrt(I(hotspot * lag(inzidenz, 1))) 
                 + sqrt(I(hotspotnb * lag(weightednbinz, 1))) + sqrt(I(rate_zweitimpf * hotspot)) 
                 + A60.79.Anteil
                 + factor(week)
                 , data =df4_pan, model = "pooling")
pool.sqrt2 <- plm(sqrt(inzidenz) ~ sqrt(lag(inzidenz, 1)) + sqrt(lag(weightednbinz, 1))
                 + I(log(density)*sqrt(lag(inzidenz, 1))) + sqrt(I(hotspot * lag(inzidenz, 1))) 
                 + sqrt(I(hotspotnb * lag(weightednbinz, 1))) + sqrt(I(rate_zweitimpf * hotspot)) 
                 + A60.79.Anteil
                 + factor(week)
                 , data =df4_pan, model = "pooling")
pool.sqrt3 <- plm(sqrt(inzidenz) ~ sqrt(lag(inzidenz, 1)) + sqrt(lag(weightednbinz, 1))
                 + sqrt(I(log(density)*lag(inzidenz, 1))) + sqrt(I(hotspot * lag(inzidenz, 1))) 
                 + sqrt(I(hotspotnb * lag(weightednbinz, 1))) + sqrt(I(rate_zweitimpf * hotspot)) 
                 + sqrt(A60.79.Anteil)
                 + factor(week)
                 , data =df4_pan, model = "pooling")



```


```{r functions, include=TRUE}
logLik.plm <- function(object){
  out <- -plm::nobs(object) * log(2 * var(object$residuals) * pi)/2 - deviance(object)/(2 * var(object$residuals))
  
  attr(out,"df") <- nobs(object) - object$df.residual
  attr(out,"nobs") <- plm::nobs(summary(object))
  return(out)
}
```


```{r AIC, include=TRUE}
stats::AIC(pool.sqrt)
stats::AIC(pool.sqrt2)
stats::AIC(pool.sqrt3)
```



```{r plots, echo=FALSE}
plot(as.vector(fitted.values(pool)), as.vector(residuals(pool)), cex.axis = 0.8,pch=16,cex=0.5, col=alpha("black",0.3))+abline(h = 0, col = adjustcolor("black",alpha=0.5), lwd = 2)

plot(as.vector(fitted.values(pool.sqrt3)), as.vector(residuals(pool.sqrt3)), cex.axis = 0.8,pch=16,cex=0.5, col=alpha("black",0.3))+abline(h = 0, col = adjustcolor("black",alpha=0.5), lwd = 2)


plot(formula=as.vector(residuals(pool.sqrt3)) ~ as.vector(fitted.values(pool.sqrt3),),
     xlab="Fitted values", ylab="Residuals",
     cex.axis=0.8, pch=16, cex=0.3, col=alpha("black",0.7)) + abline(h=0,
                                                                     col=adjustcolor("black",alpha=0.5),
                                                                     lwd=3, lty = "longdash")

plot(formula = pool.sqrt3$residuals ~ s$inzidenz1, xlab = "lag(Inzidenz, 1)",
     ylab = "Residuen", cex.axis = 0.8,pch=21,cex=0.5, col=alpha("black",0.8))+ abline(h = 0, col = adjustcolor("black",alpha=0.5), lwd = 3, lty = "longdash")

plot(formula = pool.sqrt3$residuals ~s$weightednbinz1 , xlab = "lag(gewichtete Nachbar-Inzidenzen, 1)",
     ylab = "Residuen", cex.axis = 0.8,pch=21,cex=0.5, col=alpha("black",0.8))+ abline(h = 0, col = adjustcolor("black",alpha=0.5), lwd = 3, lty = "longdash")

plot(formula = pool.sqrt3$residuals ~ s$density_inzidenz1, xlab = "log(Dichte) * lag(Inzidenz, 1) ", 
     ylab = "Residuen", cex.axis = 0.8,pch=21,cex=0.5,col=alpha("black",0.8)) +abline(h = 0, col = adjustcolor("black",alpha=0.5), lwd = 3, lty = "longdash")

plot(formula = pool.sqrt3$residuals ~ s$hotspot_inzidenz1, xlab = "Hotspot * lag(Inzidenz, 1)", 
     ylab = "Residuen", cex.axis = 0.8,pch=21,cex=0.5, col=alpha("black",0.8))+abline(h = 0, col = adjustcolor("black",alpha=0.5), lwd = 3, lty = "longdash")

plot(formula = pool.sqrt3$residuals ~ s$hotspotnb_wnbinzidenz1, xlab = "Nachbar-Hotspot * lag(gewichtete Nachbar-Inzidenzen, 1)", 
     ylab = "Residuen", cex.axis = 0.8,pch=21,cex=0.5, col=alpha("black",0.8)) +abline(h = 0, col = adjustcolor("black",alpha=0.5), lwd = 3, lty = "longdash")

plot(formula = pool.sqrt3$residuals ~ s$zweitimpf_hotspot, xlab = "Zweitimpfungrate * Hotspot",
     ylab = "Residuen", cex.axis = 0.8,pch=21,cex=0.5, col=alpha("black",0.8))+abline(h = 0, col = adjustcolor("black",alpha=0.5), lwd = 3, lty = "longdash")

plot(formula=pool.sqrt3$residuals~s$A60.79.Anteil, xlab="A60.79.Anteil", 
     ylab="Residuen", cex.axis=0.8,pch=16,cex=0.5, col=alpha("black",0.25))+abline(h = 0, col = adjustcolor("black",alpha=0.5), lwd = 3, lty = "longdash")

plot(formula = pool.sqrt$residuals ~ s$A60.79.Anteil, xlab = "A60.79.Anteil", ylab = "Residuen", cex.axis = 0.8, pch=16, cex=0.5, 
     bg="black", col=alpha("black",0.25))+ abline(h = 0, col = adjustcolor("black",alpha=0.5), lwd = 3, lty = "longdash")


```


```{r Wellen, include=TRUE}

df4 <- df4 %>% 
  mutate(Kalendarwoche = df4$week+3)


p<-c(1:9)
nullt<-subset(df4, df4$Kalendarwoche%in%p)

p<-c(9:20)
erst<-subset(df4,df4$Kalendarwoche%in%p)

p<-c(20:39)
zweit<-subset(df4,df4$Kalendarwoche%in%p)

p<-c(39:(52+8))
dritt<-subset(df4,df4$Kalendarwoche%in%p)

p<-c((52+9-1):(52+23))
viert<-subset(df4,df4$Kalendarwoche%in%p)

p<-c((52+24-1):(52+30))
fünft<-subset(df4,df4$Kalendarwoche%in%p)

p<-c((52+31-1):(52+51))
sechst<-subset(df4,df4$Kalendarwoche%in%p)

p<-c((52+52-1):(52+151))
siebt<-subset(df4,df4$Kalendarwoche%in%p)

p<-c(20:30)
zweit_a<-subset(df4,df4$Kalendarwoche%in%p)

p<-c(30:39)
zweit_b<-subset(df4,df4$Kalendarwoche%in%p)

p<-c((52+31-1):(52+39))
sechst_a<-subset(df4,df4$Kalendarwoche%in%p)

p<-c((52+40-1):(52+51))
sechst_b<-subset(df4,df4$Kalendarwoche%in%p)


df4_pan <- pdata.frame(df4, index = c("district", "week"))


nullt_pan<-pdata.frame(nullt,index=c("district","week"))

pool.nullt<-plm(inzidenz ~ lag(inzidenz, 1) + lag(weightednbinz, 1) 
                 + I(log(density)*lag(inzidenz, 1)) + I(hotspot * lag(inzidenz, 1)) 
                 +I(hotspotnb * lag(weightednbinz, 1)) 
                 + A60.79.Anteil 
                 + factor(week)
                 , data =nullt_pan, model = "pooling")

summary(pool.nullt)


pool.nullt.adj<-plm(inzidenz ~ lag(inzidenz, 1)
                 + I(log(density)*lag(inzidenz, 1)) + I(hotspot * lag(inzidenz, 1))
                 + A60.79.Anteil + A15.34.Anteil
                 + factor(week)
                 , data =nullt_pan, model = "pooling")
summary(pool.nullt.adj)
coeftest(pool.nullt.adj, vcovHC(pool.nullt.adj, type = "HC0"))


nullt_pan<-pdata.frame(nullt,index=c("district","week"))

pool.nullt<-plm(inzidenz ~ lag(inzidenz, 1) + lag(weightednbinz, 1) 
                + I(log(density)*lag(inzidenz, 1)) + I(hotspot * lag(inzidenz, 1)) 
                +I(hotspotnb * lag(weightednbinz, 1)) 
                + A60.79.Anteil 
                + factor(week)
                , data =nullt_pan, model = "pooling")

summary(pool.nullt)


erst_pan<-pdata.frame(erst,index=c("district","week"))

pool.erst<-plm(inzidenz ~ lag(inzidenz, 1) + lag(weightednbinz, 1) 
                 + I(log(density)*lag(inzidenz, 1)) + I(hotspot * lag(inzidenz, 1)) 
                 +I(hotspotnb * lag(weightednbinz, 1)) + I(rate_zweitimpf * hotspot) 
                 + A60.79.Anteil 
                 + factor(week)
                 , data =erst_pan, model = "pooling")

summary(pool.erst)



zweit_pan<-pdata.frame(zweit,index=c("district","week"))

pool.zweit<-plm(inzidenz ~ lag(inzidenz, 1) + lag(weightednbinz, 1) 
                 + I(log(density)*lag(inzidenz, 1)) + I(hotspot * lag(inzidenz, 1)) 
                 +I(hotspotnb * lag(weightednbinz, 1)) + I(rate_zweitimpf * hotspot) 
                 + A60.79.Anteil 
                 + factor(week)
                 , data =zweit_pan, model = "pooling")

summary(pool.zweit)

dritt_pan <-pdata.frame(dritt,index=c("district","week"))

pool.dritt <- plm(inzidenz ~ lag(inzidenz, 1) + lag(weightednbinz, 1) 
                 + I(log(density)*lag(inzidenz, 1)) + I(hotspot * lag(inzidenz, 1)) 
                 +I(hotspotnb * lag(weightednbinz, 1)) + I(rate_zweitimpf * hotspot) 
                 + A60.79.Anteil 
                 + factor(week)
                 , data =dritt_pan, model = "pooling")
summary(pool.dritt)



pool.viert <- plm(inzidenz ~ lag(inzidenz, 1) + lag(weightednbinz, 1) 
              + I(log(density)*lag(inzidenz, 1)) + I(hotspot * lag(inzidenz, 1)) 
              +I(hotspotnb * lag(weightednbinz, 1)) + I(rate_zweitimpf * hotspot) 
              + A60.79.Anteil 
              + factor(week)
              , data =viert, model = "pooling", index=c("district", "week"))
pool.fuenft <- plm(inzidenz ~ lag(inzidenz, 1) + lag(weightednbinz, 1) 
              + I(log(density)*lag(inzidenz, 1)) + I(hotspot * lag(inzidenz, 1)) 
              +I(hotspotnb * lag(weightednbinz, 1)) + I(rate_zweitimpf * hotspot) 
              + A60.79.Anteil 
              + factor(week)
              , data =fünft, model = "pooling", index=c("district", "week"))
pool.sechst <- plm(inzidenz ~ lag(inzidenz, 1) + lag(weightednbinz, 1) 
              + I(log(density)*lag(inzidenz, 1)) + I(hotspot * lag(inzidenz, 1)) 
              +I(hotspotnb * lag(weightednbinz, 1)) + I(rate_zweitimpf * hotspot) 
              + A60.79.Anteil 
              + factor(week)
              , data =sechst, model = "pooling", index=c("district", "week"))
pool.siebt <- plm(inzidenz ~ lag(inzidenz, 1) + lag(weightednbinz, 1) 
              + I(log(density)*lag(inzidenz, 1)) + I(hotspot * lag(inzidenz, 1)) 
              +I(hotspotnb * lag(weightednbinz, 1)) + I(rate_zweitimpf * hotspot) 
              + A60.79.Anteil 
              + factor(week)
              , data =siebt, model = "pooling", index=c("district", "week"))

pool.zweit.a <- plm(inzidenz ~ lag(inzidenz, 1) + lag(weightednbinz, 1) 
                    + I(log(density)*lag(inzidenz, 1)) + I(hotspot * lag(inzidenz, 1)) 
                    +I(hotspotnb * lag(weightednbinz, 1)) + I(rate_zweitimpf * hotspot) 
                    + A60.79.Anteil 
                    + factor(week)
                    , data = zweit_a, model = "pooling", index = c("district", "week"))
stats::AIC(pool.zweit.a)

pool.zweit.b <- plm(inzidenz ~ lag(inzidenz, 1) + lag(weightednbinz, 1) 
                    + I(log(density)*lag(inzidenz, 1)) + I(hotspot * lag(inzidenz, 1)) 
                    +I(hotspotnb * lag(weightednbinz, 1)) + I(rate_zweitimpf * hotspot) 
                    + A60.79.Anteil 
                    + factor(week)
                    , data = zweit_b, model = "pooling", index = c("district", "week"))
stats::AIC(pool.zweit.b)


pool.sechst.a <- plm(inzidenz ~ lag(inzidenz, 1) + lag(weightednbinz, 1) 
                    + I(log(density)*lag(inzidenz, 1)) + I(hotspot * lag(inzidenz, 1)) 
                    +I(hotspotnb * lag(weightednbinz, 1)) + I(rate_zweitimpf * hotspot) 
                    + A60.79.Anteil 
                    + factor(week)
                    , data = sechst_a, model = "pooling", index = c("district", "week"))
stats::AIC(pool.sechst.a)


pool.sechst.b <- plm(inzidenz ~ lag(inzidenz, 1) + lag(weightednbinz, 1) 
                     + I(log(density)*lag(inzidenz, 1)) + I(hotspot * lag(inzidenz, 1)) 
                     +I(hotspotnb * lag(weightednbinz, 1)) + I(rate_zweitimpf * hotspot) 
                     + A60.79.Anteil 
                     + factor(week)
                     , data = sechst_b, model = "pooling", index = c("district", "week"))
stats::AIC(pool.sechst.b)


sum.nullt <- summary(pool.nullt)
sum.erst <- summary(pool.erst)
sum.zweit <- summary(pool.zweit)
sum.dritt <-summary(pool.dritt)
sum.viert <-summary(pool.viert)
sum.fuenft <-summary(pool.fuenft)
sum.sechst <-summary(pool.sechst)
sum.siebt <-summary(pool.siebt)
sum.zweit.a <-summary(pool.zweit.a)
sum.zweit.b <-summary(pool.zweit.b)
sum.sechst.a <-summary(pool.sechst.a)
sum.sechst.b <-summary(pool.sechst.b)

sum.nullt$r.squared
sum.erst$r.squared
sum.zweit$r.squared
sum.dritt$r.squared
sum.viert$r.squared
sum.fuenft$r.squared
sum.sechst$r.squared
sum.siebt$r.squared
sum.zweit.a$r.squared
sum.zweit.b$r.squared
sum.sechst.a$r.squared
sum.sechst.b$r.squared



```




